import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "../lib/utils";
import QueryProvider from "../components/providers/query-provider";
import { AuthProvider } from "../components/providers/auth-provider";
import { Toaster } from "sonner";

const poppins = Poppins({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={cn(
        "h-dvh",
        "antialiased",
        poppins.className,
        "font-sans",
        poppins.variable,
        "dark",
      )}
      suppressHydrationWarning
    >
      <body className="min-h-dvh flex flex-col">
        <QueryProvider>
          <AuthProvider>{children}</AuthProvider>
        </QueryProvider>
        <Toaster closeButton position="top-center" />
      </body>
    </html>
  );
}
